apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ca
  namespace: ifba-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server   
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: minikube
        cloudNativeServices: false
        kubernetesUrl: https://192.168.49.2:8443
      vault:
        type: hashicorp
        network: fabric
        address: http://10.126.1.130:8200
        authPath: localifba
        secretEngine: secretsv2
        secretPrefix: "data/localifba"
        role: vault-role
        tls: false
      proxy:
        provider: none
        externalUrlSuffix: develop.local.com

    storage:
      size: 512Mi
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      allowedTopologies:
        enabled: false

    image:
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      ca: ghcr.io/hyperledger/bevel-fabric-ca:latest
      pullSecret: ""

    server:
      removeCertsOnDelete: true
      tlsStatus: true
      adminUsername: ifba-admin
      adminPassword: ifba-adminpw
      subject: "/C=GB/ST=London/L=London/O=Ifba/CN=ca.ifba-net"
      clusterIpPort: 7054

