apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cacarrier
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: cacarrier
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server   
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: minikube
        cloudNativeServices: false
        kubernetesUrl: https://10.32.150.94:16443
      vault:
        type: hashicorp
        network: fabric
        address: http://10.32.150.94:8200
        authPath: devcarrier
        secretEngine: secretsv2
        secretPrefix: "data/devcarrier"
        role: vault-role
        tls: false
      proxy:
        provider: haproxy
        externalUrlSuffix: org3proxy.vm1.iliada

    storage:
      size: 512Mi
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      allowedTopologies:
        enabled: false

    image:
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      ca: ghcr.io/hyperledger/bevel-fabric-ca:1.4.8
      pullSecret: ""

    server:
      removeCertsOnDelete: true
      tlsStatus: true
      adminUsername: carrier-admin
      adminPassword: carrier-adminpw
      subject: "/C=GB/ST=London/L=London/O=Carrier"
      clusterIpPort: 7054

    labels:
      service:
        - example1: example2
      pvc:
      deployment:
